Change api to use connect option conventions
mattrobenolt/connect-brotli pull request #1
Opened 2022-11-21 22:53 UTC by joshcarp

Hey!
Just opened up this pr with some changed that I think will bring the api a little closer to what connect-go uses.

Changes two things:
- `brotli.New` and `brotli.NewLevel` are renamed to `brotli.WithCompression` and `brotli.WithCompressionLevel` respectively to come closer to terminology used in connect-go around option naming.
- `brotli.WithCompression` and `brotli.WithCompressionLevel` returns a single `connect.Option` that can be passed into handler or client constructors.

Let me know what you think

2022-11-23 01:54 UTC, mattrobenolt requested changes
The rename to `WithCompression()` seems a bit odd to me as a separate library when this is the only thing this does. I get to maintain naming with core, but it makes more sense within core than this does imo.

I'm fine with it tho since I want you all to influence the nomenclature here.

2022-11-23 01:54 UTC, mattrobenolt commented on README.md
> +opts := brotli.New()
```suggestion
opts := brotli.WithCompression()
```

2022-11-23 01:54 UTC, mattrobenolt commented on README.md
> +The `brotli.New` function will return an option that allow both client and servers to compress and decompress using brotli.
```suggestion
The `brotli.WithCompression` function will return an option that allow both client and servers to compress and decompress using brotli.
```

2022-11-28 21:53 UTC, joshcarp commented
> The rename to WithCompression() seems a bit odd to me as a separate library when this is the only thing this does. I get to maintain naming with core, but it makes more sense within core than this does imo.

I mainly chose that because doing something like `brotli.WithBrotli()` would be stuttering. 
This doesn't need to be the case if you don't want to, but imo it works nicely if there are a few repos that do compression`brotli.WithCompression()` `anotherone.WithCompression()`.

2022-11-28 21:56 UTC, mattrobenolt approved these changes

2022-11-28 21:57 UTC, merged